"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 01:51:18.494425
"""
import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('managed_storage_key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_storage_key')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('permission_basis', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_installations',
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('install_location', sa.String(length=300), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=False),
    sa.Column('integrity_status', sa.String(length=20), nullable=False),
    sa.Column('license_record', sa.JSON(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('bytes_total', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_leases',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_project_id'), ['project_id'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('chapter_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_project_id'), ['project_id'], unique=False)

    op.create_table('transcriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_asset_id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('language_requested', sa.String(length=16), nullable=True),
    sa.Column('language_detected', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('timestamp_kind', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['audio_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('compatible_engine', sa.String(length=100), nullable=True),
    sa.Column('reference_asset_id', sa.String(length=32), nullable=False),
    sa.Column('reference_transcript', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('consent_record_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_asset_id'], ['audio_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('text_revision', sa.Integer(), nullable=False),
    sa.Column('voice_profile_id', sa.String(length=32), nullable=True),
    sa.Column('preset_voice', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pause_after_ms', sa.Integer(), nullable=False),
    sa.Column('selected_take_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_take_id'], ['generation_takes.id'], name='fk_segment_selected_take', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_segments_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_segments_project_id'), ['project_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('lane', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('segment_id', sa.String(length=32), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('progress_stage', sa.String(length=200), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('output_asset_id', sa.String(length=32), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['output_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['script_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['lane', 'status', 'created_at'], unique=False)

    op.create_table('generation_takes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('model_revision', sa.String(length=200), nullable=False),
    sa.Column('voice_label', sa.String(length=200), nullable=False),
    sa.Column('generation_parameters', sa.JSON(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('output_asset_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_asset_id'], ['audio_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segment_id'], ['script_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_takes_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_takes_segment_id'))

    op.drop_table('generation_takes')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_segment_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_project_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('script_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_segments_project_id'))
        batch_op.drop_index(batch_op.f('ix_script_segments_chapter_id'))

    op.drop_table('script_segments')
    op.drop_table('voice_profiles')
    op.drop_table('transcriptions')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_project_id'))

    op.drop_table('exports')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_project_id'))

    op.drop_table('chapters')
    op.drop_table('worker_leases')
    op.drop_table('projects')
    op.drop_table('model_installations')
    op.drop_table('consent_records')
    op.drop_table('audio_assets')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
